Repository second-hand-team-04/second-hand-max-be-a, pull requests merged in 2023-09, with the labels that each got.

#33 page size를 파라미터로 받도록 수정 완료
  src/main/java/com/codesquad/secondhand/api/controller/region/RegionController.java
  src/main/java/com/codesquad/secondhand/api/service/region/RegionService.java
  src/main/java/com/codesquad/secondhand/domain/common/Cursor.java
  src/main/java/com/codesquad/secondhand/exception/common/CommonExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/common/InvalidCursorException.java
  src/test/java/com/codesquad/secondhand/api/service/region/RegionServiceTest.java
Labels: refactor, week2

#34 카테고리별 지역별 상품 목록 조회 구현 완료
  build.gradle
  src/main/java/com/codesquad/secondhand/SecondHandApplication.java
  src/main/java/com/codesquad/secondhand/api/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/api/controller/item/ItemController.java
  src/main/java/com/codesquad/secondhand/api/controller/region/RegionController.java
  src/main/java/com/codesquad/secondhand/api/service/item/ItemService.java
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemResponse.java
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemSliceResponse.java
  src/main/java/com/codesquad/secondhand/config/QueryDslConfig.java
  src/main/java/com/codesquad/secondhand/domain/chat/Chat.java
  src/main/java/com/codesquad/secondhand/domain/common/Cursor.java
  src/main/java/com/codesquad/secondhand/domain/item/Item.java
  src/main/java/com/codesquad/secondhand/domain/item/ItemImage.java
  src/main/java/com/codesquad/secondhand/domain/item/ItemRepository.java
  src/main/java/com/codesquad/secondhand/domain/item/ItemStatus.java
  src/main/java/com/codesquad/secondhand/domain/item/QueryItemRepository.java
  src/main/java/com/codesquad/secondhand/domain/item/Status.java
  src/main/java/com/codesquad/secondhand/domain/user/User.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/WishList.java
  src/main/java/com/codesquad/secondhand/exception/common/CommonExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/common/InvalidCursorException.java
  src/main/java/com/codesquad/secondhand/util/BaseTimeEntity.java
  src/test/java/com/codesquad/secondhand/ControllerTestSupport.java
  src/test/java/com/codesquad/secondhand/FixtureFactory.java
  src/test/java/com/codesquad/secondhand/api/service/region/RegionServiceTest.java
Labels: feat, setting, week2

#41 사용자 회원 가입 / 로그인 기능 구현 완료
  build.gradle
  src/main/java/com/codesquad/secondhand/api/controller/auth/AuthController.java
  src/main/java/com/codesquad/secondhand/api/controller/auth/request/OAuthAccessTokenRequest.java
  src/main/java/com/codesquad/secondhand/api/controller/auth/response/OAuthAccessTokenResponse.java
  src/main/java/com/codesquad/secondhand/api/service/auth/AuthService.java
  src/main/java/com/codesquad/secondhand/api/service/auth/jwt/JwtService.java
  src/main/java/com/codesquad/secondhand/api/service/auth/oauth/KakaoClient.java
  src/main/java/com/codesquad/secondhand/api/service/auth/oauth/KakaoProperties.java
  src/main/java/com/codesquad/secondhand/api/service/auth/request/KakaoAccessTokenRequest.java
  src/main/java/com/codesquad/secondhand/api/service/auth/response/KakaoAccessTokenResponse.java
  src/main/java/com/codesquad/secondhand/api/service/auth/response/OAuthUserResponse.java
  src/main/java/com/codesquad/secondhand/api/service/user/UserService.java
  src/main/java/com/codesquad/secondhand/config/WebConfig.java
  src/main/java/com/codesquad/secondhand/config/interceptor/SignInInterceptor.java
  src/main/java/com/codesquad/secondhand/domain/auth/RefreshToken.java
  src/main/java/com/codesquad/secondhand/domain/auth/RefreshTokenRepository.java
  src/main/java/com/codesquad/secondhand/domain/provider/Provider.java
  src/main/java/com/codesquad/secondhand/domain/user/UserRepository.java
  src/main/java/com/codesquad/secondhand/util/MultiValueMapConverter.java
  src/test/java/com/codesquad/secondhand/ControllerTestSupport.java
  src/test/java/com/codesquad/secondhand/FixtureFactory.java
  src/test/java/com/codesquad/secondhand/IntegrationTestSupport.java
  src/test/java/com/codesquad/secondhand/api/service/category/CategoryServiceTest.java
  src/test/java/com/codesquad/secondhand/api/service/region/RegionServiceTest.java
  src/test/java/com/codesquad/secondhand/domain/region/RegionRepositoryTest.java
  src/test/java/com/codesquad/secondhand/domain/user/UserTest.java
  src/test/resources/schema.sql
Labels: feat, week3

#44 회원가입 path url 개방 설정
  src/main/java/com/codesquad/secondhand/api/controller/user/UserController.java
  src/main/java/com/codesquad/secondhand/config/interceptor/SignInInterceptor.java
Labels: fix, week3

#45 excludePathPatterns 설정 추가
  src/main/java/com/codesquad/secondhand/config/WebConfig.java
  src/main/java/com/codesquad/secondhand/config/interceptor/SignInInterceptor.java
Labels: fix, week3

#47 사용자 정보 조회 시 NPE 에러 수정 완료
  src/main/java/com/codesquad/secondhand/api/controller/user/response/UserInformationResponse.java
  src/main/java/com/codesquad/secondhand/domain/user/User.java
Labels: fix, week3

#49 테스트 코드 업데이트 및 추가 완료
  src/main/java/com/codesquad/secondhand/api/controller/auth/request/SignInRequest.java
  src/main/java/com/codesquad/secondhand/api/controller/category/CategoryController.java
  src/main/java/com/codesquad/secondhand/api/controller/region/RegionController.java
  src/main/java/com/codesquad/secondhand/api/controller/user/UserController.java
  src/main/java/com/codesquad/secondhand/api/controller/user/request/UserCreateRequest.java
  src/main/java/com/codesquad/secondhand/api/controller/user/response/UserInformationResponse.java
  src/main/java/com/codesquad/secondhand/api/service/auth/AuthService.java
  src/main/java/com/codesquad/secondhand/api/service/image/ImageService.java
  src/main/java/com/codesquad/secondhand/api/service/region/RegionService.java
  src/main/java/com/codesquad/secondhand/api/service/user/UserService.java
  src/main/java/com/codesquad/secondhand/api/service/user/request/UserCreateServiceRequest.java
  src/main/java/com/codesquad/secondhand/api/service/user_region/request/UserRegionCreateServiceRequest.java
  src/main/java/com/codesquad/secondhand/domain/category/Category.java
  src/main/java/com/codesquad/secondhand/domain/chat/Chat.java
  src/main/java/com/codesquad/secondhand/domain/common/Cursor.java
  src/main/java/com/codesquad/secondhand/domain/item/ItemImage.java
  src/main/java/com/codesquad/secondhand/domain/item/Status.java
  src/main/java/com/codesquad/secondhand/domain/region/Region.java
  src/main/java/com/codesquad/secondhand/domain/user/MyRegion.java
  src/main/java/com/codesquad/secondhand/domain/user/User.java
  src/main/java/com/codesquad/secondhand/domain/user/UserRepository.java
  src/main/java/com/codesquad/secondhand/domain/user_region/UserRegionRepository.java
  src/main/java/com/codesquad/secondhand/exception/common/CommonExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/common/InvalidCursorException.java
  src/test/java/com/codesquad/secondhand/ControllerTestSupport.java
  src/test/java/com/codesquad/secondhand/FixtureFactory.java
  src/test/java/com/codesquad/secondhand/api/controller/auth/AuthControllerTest.java
  src/test/java/com/codesquad/secondhand/api/controller/category/CategoryControllerTest.java
  src/test/java/com/codesquad/secondhand/api/controller/region/RegionControllerTest.java
  src/test/java/com/codesquad/secondhand/api/controller/user/UserControllerTest.java
  src/test/java/com/codesquad/secondhand/api/controller/user_region/UserRegionControllerTest.java
  src/test/java/com/codesquad/secondhand/api/service/auth/AuthServiceTest.java
  src/test/java/com/codesquad/secondhand/api/service/auth/jwt/JwtServiceTest.java
  src/test/java/com/codesquad/secondhand/api/service/category/CategoryServiceTest.java
  src/test/java/com/codesquad/secondhand/api/service/region/RegionServiceTest.java
  src/test/java/com/codesquad/secondhand/api/service/user/UserServiceTest.java
  src/test/java/com/codesquad/secondhand/domain/region/RegionRepositoryTest.java
  src/test/java/com/codesquad/secondhand/domain/user/UserRegionTest.java
  src/test/java/com/codesquad/secondhand/domain/user/UserTest.java
Labels: refactor, test, week3

#52 상품 등록/삭제/조회 API 구현 완료
  src/main/java/com/codesquad/secondhand/api/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/api/controller/image/ImageController.java
  src/main/java/com/codesquad/secondhand/api/controller/image/request/ImageRequest.java
  src/main/java/com/codesquad/secondhand/api/controller/item/ItemController.java
  src/main/java/com/codesquad/secondhand/api/controller/item/request/ItemPostingRequest.java
  src/main/java/com/codesquad/secondhand/api/controller/item/response/ItemDetailResponse.java
  src/main/java/com/codesquad/secondhand/api/controller/item/response/ItemSellerResponse.java
  src/main/java/com/codesquad/secondhand/api/controller/user_region/UserRegionController.java
  src/main/java/com/codesquad/secondhand/api/service/image/ImageService.java
  src/main/java/com/codesquad/secondhand/api/service/item/ItemService.java
  src/main/java/com/codesquad/secondhand/api/service/item/request/ItemPostingServiceRequest.java
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemResponse.java
  src/main/java/com/codesquad/secondhand/domain/item/DetailShot.java
  src/main/java/com/codesquad/secondhand/domain/item/Item.java
  src/main/java/com/codesquad/secondhand/domain/item/ItemRepository.java
  src/main/java/com/codesquad/secondhand/domain/item/QueryItemRepository.java
  src/main/java/com/codesquad/secondhand/domain/item_image/ItemImage.java
  src/main/java/com/codesquad/secondhand/domain/status/Status.java
  src/main/java/com/codesquad/secondhand/domain/status/StatusRepository.java
  src/main/java/com/codesquad/secondhand/domain/user/User.java
  src/main/java/com/codesquad/secondhand/exception/auth/AuthExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/auth/PermissionDeniedException.java
  src/main/java/com/codesquad/secondhand/exception/category/NoSuchCategoryException.java
  src/main/java/com/codesquad/secondhand/exception/image/NoSuchImageException.java
  src/main/java/com/codesquad/secondhand/exception/item/ItemExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/item/NoSuchItemException.java
  src/main/java/com/codesquad/secondhand/exception/item_image/ItemImageExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/item_image/NoSuchItemImageException.java
  src/main/java/com/codesquad/secondhand/exception/status/NoSuchStatusException.java
  src/test/java/com/codesquad/secondhand/ControllerTestSupport.java
  src/test/java/com/codesquad/secondhand/FixtureFactory.java
  src/test/java/com/codesquad/secondhand/api/controller/item/ItemControllerTest.java
  src/test/java/com/codesquad/secondhand/api/controller/user_region/UserRegionControllerTest.java
  src/test/java/com/codesquad/secondhand/api/service/item/ItemServiceTest.java
  src/test/java/com/codesquad/secondhand/domain/item/ItemTest.java
  src/test/java/com/codesquad/secondhand/domain/user/UserTest.java
Labels: feat, test, week4

#58 관심 목록 관련 API 구현 완료
  src/main/java/com/codesquad/secondhand/api/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/api/controller/wishlist/WishlistController.java
  src/main/java/com/codesquad/secondhand/api/service/user/request/UserCreateServiceRequest.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/WishlistService.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistResponse.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistSliceResponse.java
  src/main/java/com/codesquad/secondhand/domain/item/Item.java
  src/main/java/com/codesquad/secondhand/domain/item/QueryItemRepository.java
  src/main/java/com/codesquad/secondhand/domain/user/MyWishlist.java
  src/main/java/com/codesquad/secondhand/domain/user/User.java
  src/main/java/com/codesquad/secondhand/domain/user/UserRepository.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/Wishlist.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/WishlistRepository.java
  src/main/java/com/codesquad/secondhand/exception/wishlist/DuplicatedWishlistException.java
  src/main/java/com/codesquad/secondhand/exception/wishlist/NoSuchWishlistException.java
  src/main/java/com/codesquad/secondhand/exception/wishlist/WishlistExceptionHandler.java
  src/test/java/com/codesquad/secondhand/FixtureFactory.java
  src/test/java/com/codesquad/secondhand/api/service/item/ItemServiceTest.java
  src/test/java/com/codesquad/secondhand/domain/item/ItemTest.java
  src/test/java/com/codesquad/secondhand/domain/user/UserRegionTest.java
  src/test/java/com/codesquad/secondhand/domain/user/UserTest.java
Labels: feat, test, week4

#64 이미지 등록 응답 메세지 추가
  src/main/java/com/codesquad/secondhand/api/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/api/controller/image/ImageController.java
  src/main/java/com/codesquad/secondhand/api/controller/image/response/ImageResponse.java
  src/main/java/com/codesquad/secondhand/api/service/image/ImageService.java
Labels: fix, week4

#65 이미지 등록 응답 상태 수정
  src/main/java/com/codesquad/secondhand/api/controller/image/ImageController.java
Labels: fix, week4

#68 Refactor/#66 refactoring
  src/main/java/com/codesquad/secondhand/api/controller/item/ItemController.java
  src/main/java/com/codesquad/secondhand/api/controller/item/request/ItemPostRequest.java
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemResponse.java
  src/main/java/com/codesquad/secondhand/api/service/user/response/UserTransactionResponse.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistResponse.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/Wishlist.java
Labels: fix, feat, refactor

#69 Redis를 사용한 로그아웃 구현 완료
  build.gradle
  docker-compose.yml
  src/main/java/com/codesquad/secondhand/api/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/api/controller/auth/AuthController.java
  src/main/java/com/codesquad/secondhand/api/service/auth/AuthService.java
  src/main/java/com/codesquad/secondhand/api/service/auth/jwt/JwtService.java
  src/main/java/com/codesquad/secondhand/config/RedisConfig.java
  src/main/java/com/codesquad/secondhand/config/interceptor/SignInInterceptor.java
  src/main/java/com/codesquad/secondhand/domain/auth/RedisAuthRepository.java
  src/main/java/com/codesquad/secondhand/domain/auth/RefreshToken.java
  src/main/java/com/codesquad/secondhand/domain/auth/RefreshTokenRepository.java
  src/main/java/com/codesquad/secondhand/domain/item/Item.java
  src/test/java/com/codesquad/secondhand/api/controller/auth/AuthControllerTest.java
  src/test/java/com/codesquad/secondhand/api/service/auth/AuthServiceTest.java
  src/test/java/com/codesquad/secondhand/api/service/auth/jwt/JwtServiceTest.java
Labels: fix, feat, week4

#70 fix: ItemResponse 형식 수정
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemResponse.java
Labels: fix, week4

#71 fix: UserTransactionResponse 형식 수정
  src/main/java/com/codesquad/secondhand/api/service/user/response/UserTransactionResponse.java
Labels: fix, week4

#72 fix: ItemTransactionResponse 형식 수정
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemTransactionResponse.java
Labels: fix, week4

#73 ItemSellerResponse 오타 수정
  src/main/java/com/codesquad/secondhand/api/controller/item/response/ItemSellerResponse.java
Labels: fix, week4

#76 코드 수정 사항 및 프론트엔드 피드백 반영
  src/main/java/com/codesquad/secondhand/api/controller/item/ItemController.java
  src/main/java/com/codesquad/secondhand/api/controller/item/response/ItemCategoryResponse.java
  src/main/java/com/codesquad/secondhand/api/controller/item/response/ItemDetailResponse.java
  src/main/java/com/codesquad/secondhand/api/controller/item/response/ItemPostResponse.java
  src/main/java/com/codesquad/secondhand/api/controller/user/request/UserCreateRequest.java
  src/main/java/com/codesquad/secondhand/api/service/item/ItemService.java
  src/main/java/com/codesquad/secondhand/api/service/item/response/ItemResponse.java
  src/main/java/com/codesquad/secondhand/api/service/user/response/UserTransactionResponse.java
  src/main/java/com/codesquad/secondhand/domain/item/Item.java
  src/main/java/com/codesquad/secondhand/exception/CustomException.java
  src/main/java/com/codesquad/secondhand/exception/ErrorResponse.java
  src/main/java/com/codesquad/secondhand/exception/GlobalExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/user/DuplicatedEmailException.java
  src/test/java/com/codesquad/secondhand/api/controller/item/ItemControllerTest.java
  src/test/java/com/codesquad/secondhand/api/service/item/ItemServiceTest.java
  src/test/java/com/codesquad/secondhand/domain/item/ItemTest.java
Labels: fix, refactor, week5

#79 사용자 관심 목록 조회 응답 형태 수정
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistCategory.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistResponse.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/WishlistRepository.java
Labels: fix, feat, week5

#81 상품 판매 상태 검증 기능 추가 완료
  src/main/java/com/codesquad/secondhand/api/service/user/UserService.java
  src/main/java/com/codesquad/secondhand/domain/status/StatusRepository.java
Labels: feat, refactor, week5

#83 관심 목록 API 수정 및 관심 목록 카테고리 조회 API 구현
  src/main/java/com/codesquad/secondhand/api/ResponseMessage.java
  src/main/java/com/codesquad/secondhand/api/controller/wishlist/WishlistController.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/WishlistService.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/request/WishlistServiceRequest.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistCategoryResponse.java
  src/main/java/com/codesquad/secondhand/api/service/wishlist/response/WishlistResponse.java
  src/main/java/com/codesquad/secondhand/domain/category/Category.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/QueryWishlistRepository.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/Wishlist.java
  src/main/java/com/codesquad/secondhand/domain/wishlist/WishlistRepository.java
  src/test/java/com/codesquad/secondhand/domain/user/UserTest.java
Labels: fix, feat, week5

#85 선택한 사용자 동네 삭제 시 남은 동네를 자동으로 선택하도록 수정 완료
  src/main/java/com/codesquad/secondhand/domain/user/MyRegion.java
  src/main/java/com/codesquad/secondhand/domain/user/User.java
Labels: fix, week5

#89 상품 등록 관련 버그 수정 완료
  src/main/java/com/codesquad/secondhand/api/controller/item/ItemController.java
  src/main/java/com/codesquad/secondhand/api/controller/item/request/ItemPostRequest.java
  src/main/java/com/codesquad/secondhand/api/controller/item/request/ItemUpdateRequest.java
  src/main/java/com/codesquad/secondhand/api/service/item/request/ItemPostServiceRequest.java
  src/main/java/com/codesquad/secondhand/api/service/item/request/ItemUpdateServiceRequest.java
  src/main/java/com/codesquad/secondhand/exception/ErrorResponse.java
  src/main/java/com/codesquad/secondhand/exception/GlobalExceptionHandler.java
  src/main/java/com/codesquad/secondhand/exception/category/InvalidCategoryException.java
  src/test/java/com/codesquad/secondhand/api/controller/item/ItemControllerTest.java
  src/test/java/com/codesquad/secondhand/api/service/item/ItemServiceTest.java
Labels: fix, week5
